### ISSUE TITLE
IBSplot 

### ISSUE THREAD

**Issue by dosshra** [Uauy-Lab/IBSpy#19]
Hello
running: `IBSplot --IBSpy_counts "PI414721.ibs.tsv.gz" --window_size 100000 --output gmm_ibs.tsv.gz --reference ~/SV2/Wheat.Svevo.CHROMOSOMES_pacbio.fasta --query samp --plot_output gmm_plots.pdf`

I get:

> Traceback (most recent call last):
  File "/home/user/anaconda3/bin/IBSplot", line 33, in <module>
    sys.exit(load_entry_point('IBSpy', 'console_scripts', 'IBSplot')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/IBSpy/IBSpy/IBSpy_plot_window_results.py", line 29, in main
    IBS_results = IBSpyResults(args.IBSpy_counts, args.window_size, args.filter_counts)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: IBSpyResults.__init__() takes 3 positional arguments but 4 were given

Thank you

**Comment by yanyew** [comment]
I met the same issue. Have you find out the solution?

**Comment by dosshra** [comment]
I did not find a solution within ISBpy. I just loaded the results to R and made the plots there.
